#!/usr/bin/perl

use strict;
use warnings;

my $date = shift || get_date();

my $log_dir = "/Logarea/logs";
my $report  = "/monitor_rp/PORTAL/reports_monitor_" . $date . ".txt";

my %passed;

load_passed_log("$log_dir/passed.log.$date");

open(my $OUT, ">", $report) or die "Cannot create report $report : $!";

process_nopush("$log_dir/nopush.log.$date", "NOPUSH");
process_ignored("$log_dir/ignored.log.$date", "IGNORED");
process_failed("$log_dir/failed.log.$date", "FAILED");

close($OUT);

exit 0;

############################################################

sub load_passed_log
{
    my ($file) = @_;

    return unless -e $file;

    open(my $FH, "<", $file) or die "Cannot open $file : $!";

    while (my $line = <$FH>)
    {
        chomp($line);

        next unless $line =~ /\.gz$|\.txt$/i;

        $passed{$line} = 1;
    }

    close($FH);
}

############################################################

sub process_nopush
{
    my ($file, $type) = @_;
    process_simple($file, $type);
}

############################################################

sub process_ignored
{
    my ($file, $type) = @_;
    process_simple($file, $type);
}

############################################################

sub process_simple
{
    my ($file, $type) = @_;

    return unless -e $file;

    open(my $FH, "<", $file) or die "Cannot open $file : $!";

    while (my $line = <$FH>)
    {
        chomp($line);

        next unless $line eq "cdc";

        my $identifier = <$FH>;
        my $src        = <$FH>;
        my $dest       = <$FH>;
        my $date_line  = <$FH>;
        my $time_line  = <$FH>;

        chomp($identifier);
        chomp($src);
        chomp($dest);
        chomp($date_line);
        chomp($time_line);

        my $date;

        if ($date_line =~ /(\d{4}-\d{2}-\d{2})/)
        {
            $date = $1;
        }

        next if exists $passed{$src};

        print $OUT join(",",
            $type,
            $identifier,
            $src,
            $dest,
            $date,
            $time_line,
            "NA"
        ), "\n";
    }

    close($FH);
}

############################################################

sub process_failed
{
    my ($file, $type) = @_;

    return unless -e $file;

    open(my $FH, "<", $file) or die "Cannot open $file : $!";

    my $reason = "NA";

    while (my $line = <$FH>)
    {
        chomp($line);

        if ($line =~ /^#(.*)$/)
        {
            $reason = $1;
            next;
        }

        next unless $line eq "cdc";

        my $identifier = <$FH>;
        my $src        = <$FH>;
        my $dest       = <$FH>;
        my $size       = <$FH>;
        my $seconds    = <$FH>;
        my $date_line  = <$FH>;
        my $time_line  = <$FH>;

        chomp($identifier);
        chomp($src);
        chomp($dest);
        chomp($date_line);
        chomp($time_line);

        my $date;

        if ($date_line =~ /(\d{4}-\d{2}-\d{2})/)
        {
            $date = $1;
        }

        next if exists $passed{$src};

        print $OUT join(",",
            $type,
            $identifier,
            $src,
            $dest,
            $date,
            $time_line,
            $reason
        ), "\n";

        $reason = "NA";
    }

    close($FH);
}

############################################################

sub get_date
{
    my @t = localtime();

    return sprintf("%04d%02d%02d",
        $t[5] + 1900,
        $t[4] + 1,
        $t[3]);
}